openapi: 3.0.0
info:
  title: API Endpoints Validation
  version: 1.0.0
servers:
  - url: https://baseurl.com
paths:
  /api/endpoint:
    get:
      summary: Validates the correct API endpoint
      responses:
        '200':
          description: The API endpoint is correct and the request was successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Request was successful
  /api/wrong-endpoint:
    get:
      summary: Validates the incorrect API endpoint
      responses:
        '404':
          description: The API endpoint is incorrect and the request was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Request was not found
