swagger: '2.0'
info:
  title: API Endpoints Validation
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /correct-endpoint:
    get:
      summary: Validate correct API endpoint
      description: Send a GET request to the correct endpoint
      responses:
        '200':
          description: Successful response. The endpoint is correct.
  /incorrect-endpoint:
    get:
      summary: Validate incorrect API endpoint
      description: Send a GET request to the incorrect endpoint
      responses:
        '404':
          description: Unsuccessful response. The endpoint is incorrect.
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
security:
  - api_key: []
