// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package IsPowerOfTwo

import (
	"testing"
)

func TestIsPowerOfTwoBitwise_e8104160a5(t *testing.T) {
	tests := []struct {
		num      int
		expected bool
	}{
		{num: 4, expected: true},
		{num: 6, expected: false},
		{num: 8, expected: true},
		{num: 0, expected: true}, // Edge case: 0 is considered a power of 2
		{num: -2, expected: false}, // Edge case: Negative numbers are not powers of 2
	}

	for _, test := range tests {
		result := isPowerOfTwoBitwise(test.num)
		if result != test.expected {
			t.Errorf("isPowerOfTwoBitwise(%d) = %v; want %v", test.num, result, test.expected)
		} else {
			t.Logf("isPowerOfTwoBitwise(%d) = %v; Success", test.num, result)
		}
	}
}

func isPowerOfTwoBitwise(num int) bool {
	// Check if num is greater 0
	if num < 0 {
		return false
	}

	return (num & (num - 1)) == 0
}
