// Test generated by RoostGPT for test math-go using AI Type Vertex AI and AI Model code-bison

package IsPowerOfTwo

import (
	"testing"
)

func TestIsPowerOfTwo_a909b954a6(t *testing.T) {
	// Test case 1: num is a power of 2
	num := 16
	expected := true
	actual := isPowerOfTwo(num)
	if actual != expected {
		t.Errorf("Expected %t, got %t", expected, actual)
	}
}

func TestIsPowerOfTwo_b909b954a6(t *testing.T) {
	// Test case 2: num is not a power of 2
	num := 15
	expected := false
	actual := isPowerOfTwo(num)
	if actual != expected {
		t.Errorf("Expected %t, got %t", expected, actual)
	}
}
