// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package Fibonacci

import (
	"testing"
)

// TestFibonacci_3c2494e9fa tests the fibonacci function
func TestFibonacci_3c2494e9fa(t *testing.T) {

	// Test Case 1: Testing fibonacci sequence for n=10
	result := fibonacci(10)
	if result != 55 {
		t.Errorf("Test Case 1 Failed: fibonacci(10) returned: %d, expected: %d", result, 55)
	} else {
		t.Logf("Test Case 1 Passed: fibonacci(10) returned: %d", result)
	}

	// Test Case 2: Testing fibonacci sequence for n=0
	result = fibonacci(0)
	if result != 0 {
		t.Errorf("Test Case 2 Failed: fibonacci(0) returned: %d, expected: %d", result, 0)
	} else {
		t.Logf("Test Case 2 Passed: fibonacci(0) returned: %d", result)
	}

	// Test Case 3: Testing fibonacci sequence for n=1
	result = fibonacci(1)
	if result != 1 {
		t.Errorf("Test Case 3 Failed: fibonacci(1) returned: %d, expected: %d", result, 1)
	} else {
		t.Logf("Test Case 3 Passed: fibonacci(1) returned: %d", result)
	}

	// Test Case 4: Testing fibonacci sequence for n=20
	result = fibonacci(20)
	if result != 6765 {
		t.Errorf("Test Case 4 Failed: fibonacci(20) returned: %d, expected: %d", result, 6765)
	} else {
		t.Logf("Test Case 4 Passed: fibonacci(20) returned: %d", result)
	}
}
