// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package Fibonacci

import (
	"reflect"
	"testing"
)

func TestFibonacciSequence_bf4aa71a9c(t *testing.T) {
	cases := []struct {
		in   int
		want []int
	}{
		{5, []int{0, 1, 1, 2, 3, 5}},
		{10, []int{0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55}},
	}

	for _, c := range cases {
		got := fibonacci(c.in)
		if !reflect.DeepEqual(got, c.want) {
			t.Errorf("fibonacci(%q) == %q, want %q", c.in, got, c.want)
		} else {
			t.Logf("Success! fibonacci(%q) == %q", c.in, got)
		}
	}
}
