// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package Fibonacci

import (
	"testing"
)

func TestFibonacci_3c2494e9fa(t *testing.T) {
	// Test case 1: Fibonacci of 0
	result := fibonacci(0)
	if result != 0 {
		t.Errorf("Fibonacci of 0 is incorrect, got: %d, want: %d.", result, 0)
	} else {
		t.Logf("Success: Fibonacci of 0 is correct.")
	}

	// Test case 2: Fibonacci of 1
	result = fibonacci(1)
	if result != 1 {
		t.Errorf("Fibonacci of 1 is incorrect, got: %d, want: %d.", result, 1)
	} else {
		t.Logf("Success: Fibonacci of 1 is correct.")
	}

	// Test case 3: Fibonacci of 10
	result = fibonacci(10)
	if result != 55 {
		t.Errorf("Fibonacci of 10 is incorrect, got: %d, want: %d.", result, 55)
	} else {
		t.Logf("Success: Fibonacci of 10 is correct.")
	}

	// Test case 4: Fibonacci of negative number
	result = fibonacci(-5)
	if result != 0 {
		t.Errorf("Fibonacci of -5 is incorrect, got: %d, want: %d.", result, 0)
	} else {
		t.Logf("Success: Fibonacci of -5 is correct.")
	}
}
