// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package QuickSort

import (
	"reflect"
	"testing"
	"algorithms/sorting/QuickSort" // add this line to import the partion function
)

func TestPartion_04016b5112(t *testing.T) {
	type args struct {
		arr  []int
		low  int
		high int
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{
			name: "Test with positive numbers",
			args: args{
				arr:  []int{10, 80, 30, 90, 40, 50, 70},
				low:  0,
				high: 6,
			},
			want: 4,
		},
		{
			name: "Test with negative numbers",
			args: args{
				arr:  []int{-10, -80, -30, -90, -40, -50, -70},
				low:  0,
				high: 6,
			},
			want: 2,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := QuickSort.partion(tt.args.arr, tt.args.low, tt.args.high); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("partion() = %v, want %v", got, tt.want)
			} else {
				t.Logf("Success! partion() = %v, want %v", got, tt.want)
			}
		})
	}
}
