// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package QuickSort

import (
	"testing"
)

// TestPartion_04016b5112 is a test function for testing partion method
func TestPartion_04016b5112(t *testing.T) {
	// Test case 1: Normal case
	arr1 := []int{10, 80, 30, 90, 40, 50, 70}
	low1 := 0
	high1 := len(arr1) - 1
	expectedResult1 := 4
	result1 := partion(arr1, low1, high1)
	if result1 != expectedResult1 {
		t.Errorf("TestPartion_04016b5112 failed, expected: '%d', got:  '%d', values: '%v'", expectedResult1, result1, arr1)
	} else {
		t.Logf("TestPartion_04016b5112 passed, expected: '%d', got:  '%d', values: '%v'", expectedResult1, result1, arr1)
	}

	// Test case 2: Edge case where array has only one element
	arr2 := []int{1}
	low2 := 0
	high2 := len(arr2) - 1
	expectedResult2 := 0
	result2 := partion(arr2, low2, high2)
	if result2 != expectedResult2 {
		t.Errorf("TestPartion_04016b5112 failed, expected: '%d', got:  '%d', values: '%v'", expectedResult2, result2, arr2)
	} else {
		t.Logf("TestPartion_04016b5112 passed, expected: '%d', got:  '%d', values: '%v'", expectedResult2, result2, arr2)
	}
}
