// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package middleware_test

import (
	"net/http"
	"net/http/httptest"
	"testing"
	"github.com/middleware"
	"strings"
)

func TestGetAllTask(t *testing.T) {
	tests := []struct {
		name string
		request *http.Request
		wantStatusCode int
		wantBody string
	}{
		{"GetAllTask_Success", httptest.NewRequest("GET", "http://localhost:8080/tasks", nil),http.StatusOK, "testPayload"},
		// Add remaining test scenarios here
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rr := httptest.NewRecorder()

			middleware.GetAllTask(rr, tt.request)

			if status := rr.Code; status != tt.wantStatusCode {
				t.Errorf("handler returned wrong status code: got %v want %v", status, tt.wantStatusCode)
			}

			if rr.Body.String() != tt.wantBody {
				t.Errorf("handler returned unexpected body: got %v want %v",
					rr.Body.String(), tt.wantBody)
			}
		})
	}
}
